### ISSUE TITLE
Domain enquiry

### ISSUE THREAD

**Issue by Jiri-Mihal** [casanovg/itops-scripts#1]
Hi Gustavo! First of all, sorry for the off-topic message, but I haven't found any more normal way to contact you. I've tried the contact form on your ancient Tumblr blog, to comment under your 9y old YouTube video, and this is the last attempt. Why all this? I'm an indie developer working on my SaaS project, which is about bots running in the cloud. It seems you own the domain nicebots(dot)com and that should be a great name for this project. If possible, I would like to buy this domain from you. Please let me know, thank you.

**Comment by casanovg** [comment]
Hello Jiri,
Unfortunately, the domain is not for sale at the moment. Although it doesn't look like much on the surface, several services to our clients depend on it.
Regards and good luck!

**Comment by Jiri-Mihal** [comment]
Hi @casanovg, thank you for your reply, I appreciate your time. I was hoping it might be for sale, but I understand. Have a nice day👋
